version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "event-api-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dnogb7viye3j"
s3_prefix = "event-api-demo"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

